config/routes.rb
Colombiacoder::Application.routes.draw do  

  resources :profiles

  devise_for :users, :controllers => {:registrations => "registrations"}
  
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :jobs do
    put :post, on: :member
    put :expire, on: :member
    get :admin, on: :collection
    get :preview, on: :member
    post :apply, on: :member
  end
  
  resources :contacts, :only => [:index, :edit, :update]

  resources :job_types

  root :to => 'pages#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  
  has_many :technologies, :dependent => :destroy, :inverse_of => :profile
  accepts_nested_attributes_for :technologies, :allow_destroy => true, :reject_if => proc { |attributes| attributes['name'].blank? }
  attr_accessible :experience, :full_name, :professional_headline, :summary, :technologies_attributes, :technology_ids
    
  before_save :clear_skills
  after_save :add_skills
  
  def clear_skills
    # guardar los skills en una variable temporal
    @array_skills = technology_ids
    # borrar los skills del hash para que no sean creados cuando se guarda el perfil
    technology_ids = nil
  end

  def add_skills
    # asociar los skills al perfil creado 
    Technology.params_skills(@array_skills, id, 2)
  end
  
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.find(params[:id])
  end

  # GET /profiles/new
  # GET /profiles/new.json
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find(params[:id])
  end
  
  # POST /profiles
  # POST /profiles.json
  def create
    # verificar si el usuario esta logeado
    if user_signed_in?
      # si es nil el valor enviado como parametro se obtiene de session
      params[:profile] ||= session[:profile]
      # Referenciar el usuario en session
      @profile = Profile.new(params[:profile])
      if @profile.save
        session[:profile] = nil
        redirect_to @profile, notice: 'Su perfil fue creado satisfactoriamente.'
      end
    else      
      # Guardar el perfil creado en session
      session[:profile] = Profile.new(params[:profile])
      # No esta autenticado el usuario, redireccionar para crear cuenta
      redirect_to new_user_registration_path
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.json
  def update
    @profile = Profile.find(params[:id])

    if @profile.update_attributes(params[:profile])
      redirect_to @profile, notice: 'Profile was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    redirect_to profiles_url
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= simple_form_for @profile, :validate => true, :html => { :class => 'form-horizontal well' }  do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :full_name, :input_html => { :class => 'span12', :required => true } %>
    <%= f.input :professional_headline, :input_html => { :class => 'span12', :required => true } %>
    <%= f.input :experience, :input_html => { :class => 'span1 input-mini', :required => true, :type => 'number', :size => 2, :min => 0, :max => 99 } %>
    <%= f.input :summary, :input_html => { :class => 'span12', :required => true, :rows => 7 } %>
	<div class="control-group select optional">
		<label class="select optional control-label" for="profile_technology_ids">Conocimientos técnicos</label>
		<div class="controls">
			<%= f.select :technology_ids, @profile.technologies.collect {|x| [x.name, x.id]}, {}, :multiple => true, :class => 'span12' %>
			<p class="help-block">Ingrese sus conocimientos técnicos. ENTER para agregar una habilidad.</p>
		</div>
	</div>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <tr>
    <th>Full name</th>
    <th>Summary</th>
    <th>Professional headline</th>
    <th>Experience</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @profiles.each do |profile| %>
  <tr>
    <td><%= profile.full_name %></td>
    <td><%= profile.summary %></td>
    <td><%= profile.professional_headline %></td>
    <td><%= profile.experience %></td>
    <td><%= link_to 'Show', profile %></td>
    <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
    <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<br />
<div class="content">
	<div class="row-fluid">
		<h2>Perfil profesional</h2>
		<br/>
		<div class="span12">
			<%= render :partial => 'form' %>
		</div>
	</div>
</div>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Full name:</b>
  <%= @profile.full_name %>
</p>

<p>
  <b>Summary:</b>
  <%= @profile.summary %>
</p>

<p>
  <b>Professional headline:</b>
  <%= @profile.professional_headline %>
</p>

<p>
  <b>Experience:</b>
  <%= @profile.experience %>
</p>


<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>