config/routes.rb
Colombiacoder::Application.routes.draw do  

  resources :profiles

  devise_for :users, :controllers => {:registrations => "registrations"}
  
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :jobs do
    put :post, on: :member
    put :expire, on: :member
    get :admin, on: :collection
    get :preview, on: :member
    post :apply, on: :member
  end
  
  resources :contacts, :only => [:index, :edit, :update]

  resources :job_types

  root :to => 'pages#index'

end

app/models/job.rb
require 'open-uri'

class Job < ActiveRecord::Base
  
  # Dias para que una oferta laboral caduque
  DAYS_EXPIRE = 30

  # Estados de las ofertas laborales
  DEFAULT = 1
  POST = 2
  EXPIRE = 3
  
  belongs_to :user
  
  has_many :technologies, dependent: :destroy, :inverse_of => :job
  accepts_nested_attributes_for :technologies, :allow_destroy => true, :reject_if => proc { |attributes| attributes['name'].blank? }
  
  has_and_belongs_to_many :job_types
  
  has_many :seekers, :inverse_of => :job, :class_name => 'Seeker'
  accepts_nested_attributes_for :seekers
  
  # desactivado adjuntar archivos, logotipo de la empresa
  # has_attached_file :company_logo, :styles => { :medium => ["260x180>", :png], :thumb => ["160x120>", :png] }
  # validar tipo de archivo de imagen y tamanio
  # validates_attachment :company_logo, :content_type => { :content_type => ['image/jpeg', 'image/png', 'image/gif'] }, :size => { :in => 0..200.kilobytes }
   
  #reject_if evita que se envien tecnolias en blanco
 
  attr_accessible :location, :application_details, :company_description, :company_name, :company_web_site, :email_address, :no_experience_required, :job_description, 
  :job_title, :resume_directly, :salary_negotiable, :salary_range_fin, :salary_range_ini, :status, :user_id, :job_type_ids, :technologies_attributes, :technology_ids, :company_logo_url, :seekers_attributes
    
  validates :job_title, :length => { :maximum => 80 }
  validates :location, :length => { :maximum => 20 }
  
  validates :company_name, :company_description, :job_title, :job_description, :location, :job_types, :presence => true
  
  # Validar formatos de URL si existen
  validates_format_of :company_web_site, :with => URI::regexp(%w(http https)), :if => :company_web_site?
  validates_format_of :company_logo_url, :with => URI::regexp(%w(http https)), :if => :company_logo_url?
  
  # Validar como aplicar a la oferta de empleo
  validates :email_address, :email => true, :if => :resume_directly?
  validates_presence_of :application_details, :if => :application_details?

  scope :last_jobs, lambda { |num = nil| order('created_at desc').limit(num) }
  scope :urgent_jobs, lambda { |num = nil| order('created_at asc').limit(num) }
  scope :posted, where(status: 2)
  scope :recent, order('created_at desc')
  
  def self.top_location(limit)
    # seleccionar las ciudades mas ingresadas y convertir resultado en un map con solo los nombres
    connection.select_all("select location as location from (select location, count(*) from jobs group by location order by 2 desc limit #{limit}) as location").map(&:values).flatten
  end
  
  def resume_directly?
    if self.resume_directly
       self.email_address.blank?
    end
  end
  
  def application_details?
    unless self.resume_directly
       self.application_details.blank?
    end
  end

  searchable :auto_index => true, :auto_remove => true do
    # fulltext search location
    text :location
    text :job_title
    text :job_description
    
    # fulltext skills
    text :technologies do
      technologies.map { |skill| skill.name }
    end
    # rangos salariales
    integer :salary_range_ini
    integer :salary_range_fin
    # salario negociable
    boolean :salary_negotiable
    # estado de oferta laboral
    integer :status
    # tipos de contrato
    integer :job_type_ids, :multiple => true
    # fecha de creacion
    time :created_at
    # nombre de compania
    string :company_name
    # requiere experiencia
    boolean :no_experience_required
  end
  
  # Seleccionar alguna oferta laboral donde la empresa tenga un logo y tengo ofertas laborales activas
  def self.random_company_with_logo
    ids = connection.select_all("select id from jobs where company_logo_url is not null and status = 2")
    find(ids[rand(ids.length)]["id"].to_i) unless ids.blank?
  end
  
  # Copia la informacion de la ultima empresa creada
  def copy_company_information(job_from)
    # TODO: implementar
  end
  
  def expire
    # Solo si la oferta laboral esta publicada, verificar si hay que finalizarla
    if POST == status
      # verificar si ya pasaron los DAYS_EXPIRE para caducar la oferta
      days = (Time.zone.now - self.created_at).to_i / 1.day      
      # ya caduco la oferta laboral?
      if days >= DAYS_EXPIRE
        self.update_attribute(:status, EXPIRE)
      end
    end
  end
  
  def tweet!
    # Twitter oferta laboral
    tweet_desc = "Nuevo #empleo en #{location}, #{job_title}"
    shrunk_url = Job.tiny_url(134 - tweet_desc.length, "http://www.colombiacoder.com/jobs/#{id}")
    
    if tweet_desc.length > 134 - shrunk_url.length
      tweet_desc = tweet_desc[0...(134 - shrunk_url.length)] + '...'
    end
    tweet = "#{tweet_desc} #{shrunk_url}"
    Twitter.update tweet
  end
 
  def self.tiny_url(available_length, url)
    string = "http://is.gd/api.php?longurl=" + CGI::escape(url)
    open(string).read.strip
  rescue StandardError => e
    puts "Error in tiny_url: #{e.message}\n#{e.backtrace}"
  end 
  
end

app/models/job_type.rb
class JobType < ActiveRecord::Base
  
  has_and_belongs_to_many :jobs
  
  attr_accessible :name
  
  validates :name, :presence => true
  
  def to_s
    name
  end
  
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  
  include ActionView::Helpers::DateHelper

  before_filter :authenticate_user!, :except => [:show, :index, :apply]

  # GET /jobs
  def index
    # contruir objeto para inicial el formulario
    params[:job]||= {}
    @job = Job.new(params[:job])
    # Si no hay tipos de trabajo seleccionados, selecciona todos por defecto
    @job.job_types = JobType.all unless params[:job][:job_type_ids].present?
    
    search = Job.search do
      # buscar por nombre de Localizacion
      fulltext I18n.transliterate params[:job][:location] if params[:job][:location].present? do
        fields(:location)
      end
      # buscar por skills
      fulltext params[:skill] do
        fields(:technologies)
        fields(:job_title)
        fields(:job_description)
      end
      # Salario negociable
      with(:salary_negotiable, params[:job][:salary_negotiable] == 'true') if params[:job][:salary_negotiable].present?
      # Rango de salarios
      with(:salary_range_ini).greater_than(params[:job_salary_range_ini]) if params[:job][:salary_negotiable] == 'false' and params[:job_salary_range_ini].present?
      with(:salary_range_fin).less_than(params[:job_salary_range_fin]) if params[:job][:salary_negotiable] == 'false' and params[:job_salary_range_fin].present?
      # solo ofertas activas
      with(:status, 2)
      # tipos de contrato
      with(:job_type_ids, params[:job][:job_type_ids]) if params[:job][:job_type_ids].present?
      # por nombre de empresa
      with(:company_name, params[:company_name]) if params[:company_name].present?
      # Si no se requiere experiencia
      with(:no_experience_required, params[:no_experience_required]) if params[:no_experience_required].present?
      # ordernar por fecha de creacion
      order_by :created_at, :desc if params[:order] == 'last'
      order_by :created_at, :asc if params[:order] == 'urgent'
      # si no hay ningun orden por defecto ordenamos por la mas reciente
      order_by :created_at, :desc unless params[:order].present?
      # paginacion
      paginate :per_page => 20
      paginate :page => params[:page]
    end
    @jobs = search.results
    @search_total = search.total
  end
  
  # GET /jobs
  def admin
    @jobs = current_user.jobs
    # Informacion de contacto del usuario
    @contact = current_user.contact
  end

  # GET /jobs/1
  def show
    @job = Job.find(params[:id])
    # verificar si ya expira la oferta laboral
    @job.expire
    # visualizar mensaje de expiracion
    if Job::EXPIRE == @job.status
       # TODO: Enviar correo a la empresa de que finalizo la oferta, solo si la empresa esta enterado
       flash[:expire] = "<strong>Ups!</strong> esta oferta laboral caduco hace #{distance_of_time_in_words(Time.now, @job.created_at)}".html_safe
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end
  
  # GET /jobs/new
  def new
    @job = Job.new
    
    # solo si el usuario esta autenticado
    if user_signed_in?
      # verificar si existe alguna oferta laboral por defecto para traer la informacion de la empresa
      job_last = current_user.jobs.first
      if job_last
        @job.company_description = job_last.company_description
        @job.company_name = job_last.company_name
        @job.company_web_site = job_last.company_web_site
        @job.company_logo_url = job_last.company_logo_url
        @job.application_details = job_last.application_details if job_last.application_details
        @job.resume_directly = job_last.resume_directly
      end
      if current_user.email
        # verificar si el usuario tiene informacion de contacto
        @job.email_address = current_user.contact.email
        @job.location = current_user.contact.location
      end
    end
  end
  
  # POST /jobs
  def create
    # guardar los skills en una variable temporal
    array_skills = Array.new(params[:job][:technology_ids])
    # borrar los skills enviados como parametros para que no se guarden al crear la oferta
    params[:job][:technology_ids].clear
    
    # Referenciar el usuario en session
    @job = Job.new(params[:job])
    # quitar tildes en location
    @job.location = I18n.transliterate @job.location
    @job.user = current_user
    
    if @job.save
      # asociar los skills al job creado 
      Technology.params_skills(array_skills, @job.id, 1)
      # Previsualizar la oferta de empleo
      if params[:preview_button]
        redirect_to :action => 'show', :id => @job.id
      else
        redirect_to admin_jobs_path(@job.id), notice: 'Oferta laboral creada con exito.'
      end
    else
      render action: "new"
    end
  end

  # PUT /jobs/1
  def update
    @job = Job.find(params[:id])
    # editar los skills enviandos como parametros
    params[:job][:technology_ids] = Technology.params_skills(params[:job][:technology_ids], @job.id, 1)
    # quitar tildes en location
    params[:job][:location] = I18n.transliterate params[:job][:location]
    
    if @job.update_attributes(params[:job])
      redirect_to @job, notice: 'Oferta laboral actualizada.'
    else
      render action: "edit"
    end
  end

  # DELETE /jobs/1
  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to admin_jobs_url
  end
  
  # PUT /jobs/1/post
  def post
    # Cambiar de estado a publicada
    job = update_status(params[:id], 2)
    if job
      # Twitter oferta laboral
      #job.tweet!
      # redireccionar oferta laboral
      redirect_to admin_jobs_url
    else
      render action: "show"
    end
  end
  
  # PUT /jobs/1/expire
  def expire
    # Cambiar de estado a finalizada
    if update_status(params[:id], 3)
      redirect_to admin_jobs_url
    else
      render action: "show"
    end
  end
  
  def apply
    @job = Job.new(params[:job])
    @seeker = @job.seekers.first
    @seeker.job_id = params[:job][:id]
    
    if @seeker.save
      # enviar resume adjunto
      JobMailer.apply_now(@job, @seeker).deliver
      redirect_to job_path(@seeker.job_id), notice: "<i class='icon-thumbs-up'></i> Gracias por aplicar a la oferta laboral!".html_safe
      # guardar cookies de datos de envio
      cookies.permanent[:name] = @seeker.name
      cookies.permanent[:email] = @seeker.email
      cookies.permanent[:cover_letter] = @seeker.cover_letter
    else
      redirect_to job_path(@seeker.job_id), alert: "<i class='icon-warning-sign'></i> Por favor, verifique los datos ingresados e intente nuevamente!".html_safe
    end
  end
  
  private
  def update_status(job_id, status)
    @job = Job.find(job_id)
    # Cambiar de estado la oferta laboral
    @job.update_attribute(:status, status)
    # retornar oferta laboral
    @job
  end

end

app/helpers/jobs_helper.rb
module JobsHelper

  # Listado de ofertas de trabajo
  def jobs(jobs)
    raw(
      jobs.collect do |job|
        content_tag :dl do
            content_tag(:dt, (link_to job.job_title, job_path(job)))+
            content_tag(:dd, (link_to job.company_name, jobs_path({:company_name => job.company_name})))+
            content_tag(:dd, content_tag(:em, (job.location)))
        end
      end.join
    )
  end
  
  # previsualizacion de oferta de trabajo
  def job_preview(job)
    content_tag :dl do
        # Descripcion de distancia de tiempo en palabras
        content_tag(:span, "Hace #{distance_of_time_in_words(Time.now, job.created_at)}", :class => 'pull-right') +
        content_tag(:dt, (link_to job.job_title, job) + " - #{job.company_name}") + 
        content_tag(:dd, content_tag(:em, job.location)) +
        # Truncar descripcion de trabajo, quitar tags HTML
        content_tag(:dd, content_tag(:span, truncate(strip_tags(job.job_description), :length => 130), :class => 'muted')) +
        content_tag(:dd, job.job_types.to_sentence) + 
        content_tag(:dd, 
          raw(
            job.technologies.collect do |skill|
              content_tag(:span, "#{skill.name}", :class => 'label label-info') + ' '
            end.join
          )
        ) +
        content_tag(:hr)
    end
  end
  
  # Tipos de oferta de trabajo
  def setup_jobs(jobs)
    returning(jobs) do |t|
      if t.job_types.empty?
        t.job_types.build
      end
    end
  end

  # Estado de oferta laboral
  def status (job)
    content_tag :span, :class => (case job.status when 1 then 'label label-important' when 2 then 'label label-success' when 3 then 'label' end) do
      case job.status
        when 1 
          'No Publicado'
        when 2
          'Publicado'
        when 3
          'Finalizado'
      end
    end
  end
  
end

app/views/jobs/_job.html.erb
<% if flash[:expire] or flash[:notice] or flash[:alert] %>
	<div class="row-fluid">
		<div class="span12">
			<% if flash[:expire] %>
				<div class="alert">
					<%= flash[:expire] %>
				</div>
			<% elsif flash[:alert] %>
				<div class="alert alert-error">
					<%= flash[:alert] %>
				</div>
			<% elsif flash[:notice] %>
				<div class="alert alert-success">
					<%= flash[:notice] %>
				</div>
			<% end %>
		</div>
	</div>
<% end %>
<% if flash[:apply] %>
	<div class="row-fluid">
		<div class="span12">
			<div class="alert alert-success">
				<%= flash[:apply] %>
			</div>
		</div>
	</div>
<% end %>
<div class="row-fluid">
	<div class="span9">
        <h3><%= job.job_title %></h3>
		<p>
			<% job.technologies.each do |skill| %>
			<%= content_tag :span, skill.name, :class => 'label label-info' %>
			<% end %>
		</p>
		<dl class="dl-horizontal">
			<dt>
				<strong>Empresa:</strong>
			</dt>
			<dd>
				<%= link_to job.company_name, job.company_web_site, :target => '_blank' %>
			</dd>
			<dt>
				<strong>Ciudad:</strong>
			</dt>
			<dd>
				<%= job.location %>
			</dd>
			<% if job.job_types.length > 0 %>
			<dt>
				<strong>Tipo de contrato:</strong>
			</dt>
			<dd>
				<%= job.job_types.to_sentence %>
			</dd>
			<% end %>
			<dt>
				<strong>Salario:</strong>
			</dt>
			<% if job.salary_negotiable %>
			<dd>
				Negociable
			</dd>
			<% else %>
			<dd>
				<%= number_to_currency(job.salary_range_ini, :locale => :en, :unit => '$', :precision => 0).concat(' - ').concat(number_to_currency(job.salary_range_fin, :locale => :en,:unit => '$', :precision => 0)) %>
			</dd>
			<% end%>
		</dl>
	</div>
	<div class="span3">
		<% if job.company_logo_url.present? %>
		<ul class="thumbnails">
			<li class="span12">
				<div class="thumbnail">
					<%= image_tag job.company_logo_url %>
				</div>
			</li>
		</ul>
		<% end %>
	</div>
</div>
<div class="row-fluid">
	<div class="span12">
		<h4>Descripcion de la oferta</h4>
		<p>
			<%= simple_format(job.job_description) %>
		</p>
		<br/>
	</div>
</div>
<div class="row-fluid">
	<div class="span12">
		<h4>Acerca de <%= job.company_name %></h4>
		<p>
			<%= simple_format(job.company_description) %>
		</p>
		<br/>
	</div>
</div>
<% if Job::POST == job.status %>
	<% unless job.resume_directly %>
	<div class="row-fluid">
		<div class="span12">
			<div class="well">
				<h3>Como aplicar a la oferta laboral</h3>
				<p>
					<%= job.application_details %>
				</p>
			</div>
		</div>
	</div>
	<% else %>
		<%= button_tag "Aplicar", :class => 'btn btn-success btn-large', 'data-toggle' => 'modal', 'data-target' => '#modalApply' %>
		<div id="modalApply" class="modal hide fade">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
					&times;
				</button>
				<h3><%= job.job_title %></h3>
				<h4><%= job.company_name %></h4>
			</div>
			<%= simple_form_for job, :url => apply_job_path(job), :method => :post, :html => { :multipart => true } do |f| %>
				<%= f.input :job_title, :as => :hidden %>
				<%= f.input :email_address, :as => :hidden %>
				<%= f.input :id, :as => :hidden %>
				<%= f.simple_fields_for :seekers, job.seekers.build do |s| %>
					<div class="modal-body">
						<p>
							<%= s.error_notification %>
							<div class="form-inputs">
							  	<%= s.input :name, :autofocus => true, :input_html => { :class => 'span12', :value => cookies[:name] }, :label => false, :required => true %>
								<%= s.input :email, :input_html => { :class => 'span12', :value => cookies[:email] }, :label => false %>
								<%= s.input :cover_letter, :as => :text, :input_html => { :rows => 5, :class => 'span12', :value => cookies[:cover_letter] }, :label => false %>
								<div class="alert alert-info">
									Adjunte su currículum en formato <span class="badge badge-important">PDF</span> o <span class="badge badge-info">MS Word</span>
									<%= s.file_field :resume %>
								</div>
								<%= s.input :notification, :wrapper => :inline_checkbox, :as => :boolean %>
							</div>
						</p>
					</div>
				<% end %>
				<div class="modal-footer">
					<%= f.button :submit, 'Enviar', :class => 'btn btn-info', :name => nil %>
				</div>
			<% end %>
		</div>
	<% end %>
<% end %>

app/views/jobs/admin.html.erb
<%- model_class = Job.new.class -%>
<div class="row-fluid">
	<div class="span9">
		<div class="page-header">
			<h2>Mis ofertas laborales</h2>
		</div>
		<p class="pull-right">
			<%= link_to 'Publicar nueva oferta', new_job_path, :class => 'btn btn-info' %>
		</p>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Oferta Laboral</th>
					<th>Estado de publicación</th>
					<th>Opciones</th>
				</tr>
			</thead>
			<tbody>
				<% @jobs.each do |job| %>
				<tr>
					<td><%= link_to job.job_title, job_path(job) %></td>
					<td><%= status(job) %></td>
					<td>
					<div class="btn-group">
						<%= link_to 'Editar', edit_job_path(job), :class => 'btn' %>
						<button class="btn dropdown-toggle" data-toggle="dropdown">
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu">
							<% if Job::DEFAULT == job.status %>
							<li>
								<%= link_to 'Publicar', post_job_path(job), :method => :put, :confirm => 'Su oferta laboral sera publicada por un periodo de 30 dias, pasado este tiempo finalizara automáticamente.' %>
							</li>
							<% end %>
							<% if Job::DEFAULT == job.status or Job::EXPIRE == job.status %>
							<li>
								<%= link_to 'Eliminar', job_path(job), :method => :delete, :confirm => 'Su oferta laboral sera eliminada permanentemente, esta seguro?' %>
							</li>
							<% end %>
							<% if Job::EXPIRE == job.status %>
							<li>
								<%= link_to 'Republicar', post_job_path(job), :method => :put %>
							</li>
							<% end %>
							<% if Job::POST == job.status %>
							<li>
								<%= link_to 'Finalizar', expire_job_path(job), :method => :put %>
							</li>
							<% end %>
						</ul>
					</div></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
	<div class="span3">
		<%= render @contact %>
		<br />
		<br />
		<script type="text/javascript"><!--
		google_ad_client = "ca-pub-9287817861975219";
		/* COLDEV_ADMIN */
		google_ad_slot = "2568379694";
		google_ad_width = 250;
		google_ad_height = 250;
		//-->
		</script>
		<script type="text/javascript"
		src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
		</script>
	</div>
</div>

app/views/jobs/edit.html.erb
<%- model_class = @job.class -%>
<div class="content">
	<div class="row">
		<div class="span12">
			<ul class="breadcrumb">
				<li>
					<%= link_to "Mis ofertas laborales", admin_jobs_path %><span class="divider">/</span>
				</li>
				<li>
					Crear una oferta de empleo<span class="divider">/</span>
				</li>
				<li class="active">
					Vista previa
				</li>
			</ul>
		</div>
		<div class="span12">
			<div class="row-fluid">
				<%= render :partial => 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/jobs/preview.html.erb
<div class="content">
	<div class="row">
		<div class="span12">
			<ul class="breadcrumb">
				<% if user_signed_in? %>
					<li>
						<%= link_to "Mis ofertas laborales", admin_jobs_path %><span class="divider">/</span>
					</li>
				<% end %>
				<li>
					<%= link_to 'Crear una oferta de empleo', new_job_path %><span class="divider">/</span>
				</li>
				<li class="active">
					Vista previa
				</li>
			</ul>
		</div>
		<div class="span12">
			<div class="alert alert-info">
				<h4>Vista previa de su oferta laboral</h4>
				<p>
					Aquí está una vista previa de su oferta laboral. Puede editar nuevamente la informacion, luego puedes dar click en "Publicar oferta laboral" cuando estás satisfecho.
				</p>
				<p>
					<%= form_tag(@job) do -%>
						<%= link_to 'Continuar editando', edit_job_path(@job), :class => 'btn' %>
						<%= button_tag(type: 'submit', :class => 'btn btn-info', :name => 'post_button') do %>
						    <i class=" icon-pencil"></i> Publicar oferta
						<% end %>
					<% end -%>
				</p>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<%= render @job %>
		</div>
	</div>
</div>

app/views/jobs/show.html.erb
<div class="content">
	<div class="row">
		<% if user_signed_in? and current_user.id == @job.user_id %>
			<div class="span12">
				<ul class="breadcrumb">
					<li>
					<%= link_to "Mis ofertas laborales", admin_jobs_path %><span class="divider">/</span>
				</li>
				<li>
					<%= link_to "Crear una oferta de empleo", edit_job_path %><span class="divider">/</span>
				</li>
				<li class="active">
					Vista previa
				</li>
				</ul>
			</div>
			<div class="span12">
				<div class="alert alert-success">
					<h4>Vista previa de su oferta laboral</h4>
					<p>
						Aquí está una vista previa de su oferta laboral. Puede editar nuevamente la informacion, luego puedes dar click en "Publicar oferta laboral" cuando estás satisfecho.
					</p>
					<p>
						<%= link_to 'Editar', edit_job_path(@job), :class => 'btn' %>
						<% if @job.status == 1 %>
							<%= link_to 'Publicar oferta', '#confirmModal', :class => 'btn btn-success', :role => 'button', 'data-toggle' => 'modal' %>
						<% end %>
						<% if @job.status == 3 %>
							<%= link_to 'Republicar oferta', post_job_path(@job), :class => 'btn btn-info', :method => :put %>
						<% end %>
					</p>
				</div>
				<p>Estado de oferta laboral: <%= status (@job) %></p>
				<div id="confirmModal" class="modal hide fade">
					<div class="modal-header">
				    	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				    	<h3>Publicación de oferta</h3>
				  	</div>
				  	<div class="modal-body">
  						<p>Su oferta laboral sera publicada por un periodo de <strong>30 días</strong>, pasado este tiempo finalizara automáticamente.</p>
  						<p>Puede republicar, finalizar o eliminar sus ofertas laborales desde la opción <strong>Mis ofertas laborales</strong></p>
				  	</div>
				  	<div class="modal-footer">
						<%= link_to 'Publicar', post_job_path(@job), :class => 'btn btn-info', :method => :put %>
				  	</div>
				</div>
			</div>
		<% end %>
	</div>
	<div class="row-fluid">
		<div class="span9">
			<%= render @job %>
		</div>
		<div class="span3">
			<!-- Facebook -->
			<div id="fb-root"></div>
				<script>(function(d, s, id) {
				  var js, fjs = d.getElementsByTagName(s)[0];
				  if (d.getElementById(id)) return;
				  js = d.createElement(s); js.id = id;
				  js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1";
				  fjs.parentNode.insertBefore(js, fjs);
				}(document, 'script', 'facebook-jssdk'));
			</script>
			<!-- Twittear -->
			<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			<div class="alert alert-success">
				<h4 class="page-header">Comparte la información</h4>
					<p>
						<small>¿Conoces a alguien con los conocimientos técnicos?. Comparte la información!</small>
					</p>
				<div class="btn-group">
					<div class="fb-like" data-send="true" data-layout="button_count" data-width="450" data-show-faces="false" data-action="recommend"></div>
					<div><a href="https://twitter.com/share" class="twitter-share-button" data-text="Se solicitan ingenieros con talento en la industria del software en Colombia" data-lang="es" data-hashtags="empleo">Twittear</a></div>
					<div class="g-plus" data-action="share"></div>
				</div>
			</div>
			<!-- Google plus -->
			<script type="text/javascript">
			  window.___gcfg = {lang: 'es-419'};
			
			  (function() {
			    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
			    po.src = 'https://apis.google.com/js/plusone.js';
			    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
			  })();
			</script>
			<br/>
			<script type="text/javascript"><!--
			google_ad_client = "ca-pub-9287817861975219";
			/* COLDEV_SHOW */
			google_ad_slot = "7473716955";
			google_ad_width = 160;
			google_ad_height = 600;
			//-->
			</script>
			<script type="text/javascript"
			src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
			</script>
		</div>
	</div>
</div>