config/routes.rb
Colombiacoder::Application.routes.draw do  

  resources :profiles

  devise_for :users, :controllers => {:registrations => "registrations"}
  
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :jobs do
    put :post, on: :member
    put :expire, on: :member
    get :admin, on: :collection
    get :preview, on: :member
    post :apply, on: :member
  end
  
  resources :contacts, :only => [:index, :edit, :update]

  resources :job_types

  root :to => 'pages#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  
  belongs_to :user, :polymorphic => true
  
  attr_accessible :company, :email, :full_name, :phone, :street_address, :web_site, :location
  
  validates :email, :email => true, :uniqueness => { :case_sensitive => false }
  
  # Validar formatos de URL si existen
  validates_format_of :web_site, :with => URI::regexp(%w(http https)), :if => :web_site?
 
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  before_filter :authenticate_user!
  
  # GET /contacts
  # GET /contacts.json
  # Solo administrador
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
    # current_user.contact
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = current_user.contact
    if @contact.update_attributes(params[:contact])
      redirect_to admin_jobs_path, notice: 'Informacion de contacto actualizada satisfactoriamente.'
    else
      render action: "edit"
    end
  end
  
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contact.html.erb
<div class="page-header">
	<h4>Información de contacto</h4>
</div>
<address>
	<% if contact.full_name.present? %>
		<strong><%= contact.full_name %></strong>
	<% else  %>
		<em class="muted">Sin nombre de contacto</em>
	<% end %>
	<br>
	<% if contact.email.present? %>
		<%= link_to contact.email, "mailto: #{@contact.email}" %>
	<% else  %>
		<em class="muted">Sin email</em>
	<% end %>
	<br>
	<% if contact.phone.present? %>
		<abbr title="Phone">Tel.</abbr> <%= @contact.phone %>
	<% else  %>
		<em class="muted">Sin teléfono</em>
	<% end %>
</address>
<address>
	<% if contact.company.present? %>
		<strong><%= contact.company %></strong>
	<% else  %>
		<em class="muted">Sin información de la empresa</em>
	<% end %>
	<br>
	<% if contact.web_site.present? %>
		<%= link_to contact.web_site, "#{@contact.web_site}" %>
	<% else  %>
		<em class="muted">Sin sitio web</em>
	<% end %>
	<br>
	<% if contact.street_address.present? %>
		<%= contact.street_address %>
	<% else  %>
		<em class="muted">Sin dirección</em>
	<% end %>
	<br>
	<% if contact.location.present? %>
		<%= contact.location %>
	<% else  %>
		<em class="muted">Sin Ciudad</em>
	<% end %>
</address>
<%= link_to 'Editar informacion de contacto', edit_contact_path(contact.id) %>

app/views/contacts/_form.html.erb
<%= simple_form_for @contact, :validate => true, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-inputs">
	  <%= f.input :full_name, :class => 'text_field' %>
	  <%= f.input :email, :class => 'text_field' %>
	  <%= f.input :company, :class => 'text_field' %>
	  <%= f.input :web_site, :class => 'text_field' %>
	  <%= f.input :location, :class => 'text_field' %>
	  <%= f.input :street_address, :class => 'text_field' %>
	  <%= f.input :phone, :class => 'text_field' %> 
  </div>
  <div class="form-actions">
  	<%= f.button :submit, 'Actualizar', :class => 'btn btn-info' %>
    <%= link_to 'Cancelar', admin_jobs_path, :class => 'btn' %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<%- model_class = @contact.class -%>
<div class="page-header">
  <h2>Editar informacion de contacto</h2>
</div>
<div class="alert alert-warning">
	<strong><i class="icon-warning-sign"></i> Aviso Legal!</strong>
	Su información no será suministrada o compartida con ninguna persona, negocio u organización.
</div>
<%= render :partial => 'form' %>

app/views/contacts/index.html.erb
<%- model_class = Contact.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:full_name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:company) %></th>
      <th><%= model_class.human_attribute_name(:web_site) %></th>
      <th><%= model_class.human_attribute_name(:street_address) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= link_to contact.id, contact_path(contact) %></td>
        <td><%= contact.full_name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.company %></td>
        <td><%= contact.web_site %></td>
        <td><%= contact.street_address %></td>
        <td><%= contact.phone %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_contact_path(contact), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      contact_path(contact),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_contact_path,
            :class => 'btn btn-info' %>