config/routes.rb
Colombiacoder::Application.routes.draw do  

  resources :profiles

  devise_for :users, :controllers => {:registrations => "registrations"}
  
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :jobs do
    put :post, on: :member
    put :expire, on: :member
    get :admin, on: :collection
    get :preview, on: :member
    post :apply, on: :member
  end
  
  resources :contacts, :only => [:index, :edit, :update]

  resources :job_types

  root :to => 'pages#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="Accede a oportunidades laborales en la industria del software en Colombia" >
		<meta name="keywords" content="bolsas de empleo,vacantes de empleo,ofertas de empleo,empleos medio tiempo,ofertas de trabajo,empleo,trabajo,trabajos,job,freelance,medio tiempo,php,java freelance,c# freelance,software,software developer,java developer,estudiantes universitarios,freelancer,coder,programadores,programar">

		<title><%= content_for?(:title) ? yield(:title) : "Ofertas de empleo en Software en Colombia" %></title>
		<%= csrf_meta_tags %>

		<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
		<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
		<![endif]-->

		<%= stylesheet_link_tag "application", :media => "all" %>
		
		<link href="/assets/favicon.ico" rel="shortcut icon">
		<link href="/assets/colombiacoder-icon.png" rel="apple-touch-icon">
		<link href="/assets/colombiacoder-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
		<link href="/assets/colombiacoder-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
	</head>
	<body>
		<!-- Google Tag Manager -->
		<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-LQ79"
		height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
		<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
		new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
		j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
		'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
		})(window,document,'script','dataLayer','GTM-LQ79');</script>
		<!-- End Google Tag Manager -->
		<div class="navbar navbar-fixed-top">
			<div style="background: #f5f5f5">
				<div class="container">
					<div class="row">
						<div class="span2">
							<%= link_to image_tag('logo_colombiacoder.png'), root_path %>
						</div>
						<div class="span8" style="padding-top: 5px;">
							<!-- Publicidad -->
							<script type="text/javascript"><!--
								google_ad_client = "ca-pub-9287817861975219";
								/* COLDEV_SEARCH2 */
								google_ad_slot = "0245526804";
								google_ad_width = 728;
								google_ad_height = 90;
								//-->
								</script>
								<script type="text/javascript"
								src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
							</script>
						</div>
						<div class="span2">
							<div class="pull-right">
								<br/>
								<!-- AddThis Follow BEGIN -->
								<div class="addthis_toolbox addthis_32x32_style addthis_default_style">
								<a class="addthis_button_facebook_follow" addthis:userid="colombiacoder"></a>
								<a class="addthis_button_twitter_follow" addthis:userid="colombiacoder"></a>
								</div>
								<script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5057a9c50c97cff8"></script>
								<!-- AddThis Follow END -->
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="navbar-inner">
				<div class="container">
					<a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</a>
					<%= link_to 'Página principal', root_path, :class => 'brand' %>
					<div class="nav-collapse">
						<ul class="nav">
							<li>
								<%= link_to 'Búsqueda de ofertas laborales', jobs_path %>
							</li>
							<li>
								<!-- // MAILCHIMP SUBSCRIBE CODE \\ -->
								<%= link_to '¿Ya tienes trabajo?', 'http://eepurl.com/pshxX' %>
								<!-- \\ MAILCHIMP SUBSCRIBE LINK // -->
							</li>
						</ul>
						<% unless user_signed_in? %>
							<ul class="nav pull-right">
			                	<%= link_to 'Iniciar sesión', new_user_session_path, :class => 'btn btn-small btn-small' %>
								<%= link_to 'Crear una cuenta', new_user_registration_path, :class => 'btn btn-small btn-success' %>
							</ul>
						<% end %>
						<% if user_signed_in? %>
							<ul class="nav pull-right">
		                   		<li class="dropdown">
		                        	<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= (current_user.contact.full_name.presence || current_user.contact.email.presence) %> <b class="caret"></b></a>
		                        	<ul class="dropdown-menu">
		                          		<li><%= link_to "Mis ofertas laborales", admin_jobs_path %></li>
		                          		<li><%= link_to "Editar cuenta", edit_user_registration_path %></li>
		                          		<li><%= link_to "Salir", destroy_user_session_path, :method => :delete %></li> 
		                        	</ul>
		                    	</li>
		                    </ul>
		               <% end %>
					</div>
				</div>
			</div>
		</div>

		<div class="container">
			<%= yield %>
		</div>
		
		<!-- /container -->
		
		<footer class="footer">
			<div class="container">
				<p style="text-align: center;">
					Oportunidades laborales para la industria del software - &copy; ColombiaCoder 2012<br/>
					Teléfono: (57) (312) 2575823 - Bogotá - Colombia - Correo: info@colombiacoder.com
				</p>
				<br/>
				<div style="text-align: center">
					<script type="text/javascript" language="JavaScript" src="http://colombiacoder.us5.list-manage.com/subscriber-count?b=21&u=f05db4a9-d936-46f7-bebd-e99e596935da&id=9436ce4e90"></script>
				</div>
			</div>
		</footer>

		<!-- Javascripts
		================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<%= javascript_include_tag 'jquery', 'rails.validations'-%>
		<%= javascript_include_tag "application" %>
		<% javascript_tag :defer => 'defer' do -%>
		<% end -%>
	</body>
</html>